# proxy_buffering off is required for SSE token streaming to work 
# SSE is browser protocl: server keeps HTTP connection open 

location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host      $http_host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_connect_timeout 600;
    proxy_send_timeout    600;
    proxy_read_timeout    600;
    send_timeout          600;
    # By default, nginx collects entire server resposne into a buffer before browser forwarding
    # proxy_buffer on: user sees nothing until full response. NO STREAMING.
    # Proxy_buffer off: nginx forwards bytes as they arrive

    proxy_buffering off;
    proxy_pass http://127.0.0.1:5050/;
}
